from setuptools import find_packages, setup

package_name = 'my_py_drone_pkg'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='emeka',
    maintainer_email='emeka@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            "py_node = my_py_drone_pkg.my_first_node:main",
            "takeoff = my_py_drone_pkg.takeoff:main",
            "drone_state_listener = my_py_drone_pkg.drone_state_listener:main",
            "drone_state_listener_2 = my_py_drone_pkg.drone_state_listner_2:main",
            "offboard_control = my_py_drone_pkg.offboard_control:main",
            "offboard_control_ver2 = my_py_drone_pkg.offboard_control_ver2:main",
            "proto_off = my_py_drone_pkg.proto_off:main",
            "movement = my_py_drone_pkg.movement:main",
            "mavros_state_subscriber = my_py_drone_pkg.mavros_subscriber:main",
            "mavros_flight_example = my_py_drone_pkg.mavros_flight_example:main",
            "offb_node = my_py_drone_pkg.offb_node:main",
            "takeoff_mav = my_py_drone_pkg.takeoff_mav:main",
            "real_example = my_py_drone_pkg.real_example:main",
            "real_version2 = my_py_drone_pkg.real_example_2:main",
            "real_drone_movement = my_py_drone_pkg.real_drone_movement:main",
            "takeoff_land = my_py_drone_pkg.real_movement:main",
            "move_2_drones = my_py_drone_pkg.real_movement_2_drones:main",
            "concurrent_control = my_py_drone_pkg.concurrent_control_of_2_drones:main",
            "concurrent_control_ver2 = my_py_drone_pkg.concurrent_control_of_2_drones_ver2:main",
            "multi_trhd_2_drones = my_py_drone_pkg.multi_exec_2_drones:main",
            "jumping_person = my_py_drone_pkg.jumping_example:main",
            "multi_async_drones = my_py_drone_pkg.multi_async_drones:main",
            "multi_async_drones_retrn = my_py_drone_pkg.multi_async_drones_retrn:main",
            "leader_follower = my_py_drone_pkg.leader_2_follower:main",
            "multiple_waypoint = my_py_drone_pkg.multi_waypoint:main",
            "full_drn_cntrl = my_py_drone_pkg.full_cntrl_1drn:main",
            "topic_lister = my_py_drone_pkg.topic_list_maker:main",
            "drone_pos_rec = my_py_drone_pkg.drone_position_record:main",
            "drone_pos_rec_2 = my_py_drone_pkg.drone_position_record_2:main",
            "drone_pos_rec_3 = my_py_drone_pkg.drone_position_record_3:main",
            "formation_drones = my_py_drone_pkg.formation_of_drones:main",
            "formation_drones_2 = my_py_drone_pkg.formation_of_drones_with_seperation:main",
            "simple_follower = my_py_drone_pkg.simple_follow_drone:main",
            "manual_follower = my_py_drone_pkg.simple_follow_drone_2:main",
            "advance_follower = my_py_drone_pkg.simple_follow_drone_3_wth_avoid:main",
            "fly_4_drones = my_py_drone_pkg.fly_with_4drones:main",
            "fly_5_drones = my_py_drone_pkg.fly_with_5drones:main",
        ],
    },
)
